name: Feature Request
description: Suggest a new feature or improvement!
labels: [enhancement, codex]
assignees: [lunamidori5]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe the feature you'd like to see and why.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Describe the problem or pain point this feature would solve.
      placeholder: What's the issue you're facing?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like and how it should work.
      placeholder: How should this behave?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternatives or existing workarounds.
      placeholder: Other approaches you've considered.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or links that would help.
      placeholder: Screenshots, designs, or references.
    validations:
      required: false
